### ISSUE TITLE
Text filter is not working

### ISSUE THREAD

**Issue by HubKing** [sboulema/CodeNav#14] opened 2017-02-24 06:25 UTC
1. Text filter is not working at all. I typed a few letters, nothing happened. I pressed the enter key, still nothing happened.

2. After typing something, clicking the "Clear text filter" twice crashes Visual Studio.

3. Under Dark theme, text and the cursor inside the text filter are practically invisible because they are black.

**Comment by sboulema** [comment] 2017-02-24 08:26
Thanks for reporting this issue!

I am unfortunately unable to reproduce 1. and 2. Can you provide the file in which they filter is not working, or a minimal code sample to reproduce it?

3. has been fixed in the new release :D

**Comment by HubKing** [comment] 2017-02-24 09:40
It seems to happen intermittently with Visual Studio 2017 RC 4. It happened with the ["TreeViewAdv.cs"](https://sourceforge.net/projects/treeviewadv/). I have tried several times, but still am not sure of the exact condition for it. I will let you know if I find it. The only suspicious thing about the class is that the class is a partial class that spans multiple files.

**Comment by sboulema** [comment] 2017-02-28 09:34
Thanks for providing the file. I am now able to reproduce the error and am working on a fix :)

**Comment by sboulema** [comment] 2017-02-28 16:52
This is now fixed in the upcoming release!

**Closed by sboulema** 2017-02-28 16:52 UTC
Labels: bug
